# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.4
  - 1.5
  - nightly
notifications:
  email: false
jobs:
  allow_failures:
    - julia: nightly, 1.5
  fast_finish: true
