name = "Nas"
uuid = "4fad0199-730a-4124-aed3-2f66c9290c01"
authors = ["nik "]
version = "0.1.0"

[compat]
julia = "1.3.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
